swagger: "2.0"
info:
  title: Mavericks Back-End API
  description: backend API documentation for Mavericks e-commerce
  version: 1.0

paths:
  /:
    get:
      summary: returns entry page.
      description: get api for the first page.
      responses:
        200:
          description: Successful Response

  /api/users:
    post:
      summary: Create a new user
      description: Endpoint to create a new user
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: user
          description: The user object
          required: true
          schema:
            $ref: "#/definitions/UserRequest"
      responses:
        201:
          description: User created successfully
          schema:
            $ref: "#/definitions/UserResponse"
        400:
          description: Bad request, invalid user data provided
        500:
          description: Internal server error

definitions:
  UserRequest:
    type: object
    properties:
      firstName:
        type: string
        description: The first name of the user
      lastName:
        type: string
        description: The last name of the user
      email:
        type: string
        format: email
        description: The email address of the user
      password:
        type: string
        description: The password of the user
      gender:
        type: string
        enum: ["Male", "Female"]
        description: The gender of the user
      phoneNumber:
        type: string
        description: The phone number of the user
    required:
      - firstName
      - lastName
      - email
      - password
      - gender
      - phoneNumber

  UserResponse:
    type: object
    properties:
      id:
        type: string
        description: The unique identifier of the user
      verified:
        type: boolean
        description: Whether the user is verified or not
      firstName:
        type: string
        description: The first name of the user
      lastName:
        type: string
        description: The last name of the user
      email:
        type: string
        format: email
        description: The email address of the user
      password:
        type: string
        description: The hashed password of the user
      gender:
        type: string
        enum: ["Male", "Female"]
        description: The gender of the user
      phoneNumber:
        type: string
        description: The phone number of the user
      updatedAt:
        type: string
        format: date-time
        description: The timestamp when the user was last updated
      createdAt:
        type: string
        format: date-time
        description: The timestamp when the user was created
      photoUrl:
        type: string
        description: The URL of the user's photo
      googleId:
        type: string
        description: The Google ID of the user