version: '3.8'
services:
  backend:
    container_name: backend
    image: 'backend:v1'
    build: .
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
  db:
    container_name: db
    image: 'postgres:13'
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - backend:/var/lib/postgresql/data

volumes:
  backend:
